apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave
  namespace: default
subjects:
  - kind: ServiceAccount
    name: dave
    apiGroup: ""
    namespace: default
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
